import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import React from "react";

const inter = Montserrat({ subsets: [] });

export const metadata: Metadata = {
  title: "Solar las Marías",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-CO" className="scroll-smooth">
      <body className={`${inter.className} scroll-smooth`}>{children}</body>
    </html>
  );
}
